In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [5]:
import numpy as np
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,0]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [12]:
#creating numpy array
np.arange(0,10) #evenly spaced from start to finish, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2) #steps of 2

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#arrays of all 0s
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5)) #first number is number of rows, second is number of columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
#lint space - returns evenly spaced values, but takes in number of points we want
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
#identity matrix - matrix for linear algebra, 2d square matrix and a diagonal of 1s, rest are 0s
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
#arrays of random numbers
np.random.rand(5) #1 dimensional

array([0.2100432 , 0.6098043 , 0.08667158, 0.45762826, 0.60586843])

In [25]:
np.random.rand(5,5) #2dimensional

array([[0.71724374, 0.89100286, 0.60966047, 0.7600261 , 0.27372476],
       [0.08167824, 0.23665788, 0.80355489, 0.43152707, 0.83662576],
       [0.38256085, 0.12940771, 0.85343402, 0.67917902, 0.65442558],
       [0.01582597, 0.68891159, 0.72617075, 0.83677719, 0.95805492],
       [0.02913922, 0.88968616, 0.30703097, 0.95164471, 0.29878548]])

In [26]:
np.random.randn(2) #2 random numbers from standard gaussian distribution, centered around 0

array([0.05515197, 0.14423521])

In [27]:
np.random.randn(4,4) #make it a 2d array centered at 0 - gaussian 

array([[ 1.10586079, -2.05197189,  0.63247178,  0.33043879],
       [-1.00803687, -0.64742884, -1.46658262, -0.57375428],
       [ 1.48190954,  2.72780203,  0.0607247 ,  1.23394243],
       [-1.27817277, -0.57783028, -0.17908837,  1.18631028]])

In [28]:
np.random.randint(1,100) #random integer from 1-100. 1 has a chance to be selected, but 100 doesn't

79

In [29]:
np.random.randint(1,100,10) #10 random integers, but not 100

array([61, 61,  7,  9, 81, 41, 10, 44, 57,  8])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([48, 30, 19,  7,  2, 15, 42, 41, 29, 33])

In [34]:
#reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
#man/min values
ranarr

array([48, 30, 19,  7,  2, 15, 42, 41, 29, 33])

In [37]:
#find max value
ranarr.max()

48

In [38]:
#find min value
ranarr.min()

2

In [39]:
#find max/min value in the array - index value
ranarr.argmax()

0

In [40]:
ranarr.argmin()

4

In [42]:
#shape of a vector
arr.shape #outputs (25,) because arr is a 1 dimensional vector

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape #now it's 2 dimensional

(5, 5)

In [47]:
#data type of array
arr.dtype

dtype('int32')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)

4